// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommentCreateRequest struct {
	// UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Story UUID
	StoryId string `protobuf:"bytes,2,opt,name=storyId,proto3" json:"storyId,omitempty"`
	// comment content
	TextContent string `protobuf:"bytes,3,opt,name=textContent,proto3" json:"textContent,omitempty"`
	// Commented by
	Commentator string `protobuf:"bytes,4,opt,name=commentator,proto3" json:"commentator,omitempty"`
	// Create time
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommentCreateRequest) Reset()         { *m = CommentCreateRequest{} }
func (m *CommentCreateRequest) String() string { return proto.CompactTextString(m) }
func (*CommentCreateRequest) ProtoMessage()    {}
func (*CommentCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_359215752d6d6d81, []int{0}
}

func (m *CommentCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentCreateRequest.Unmarshal(m, b)
}
func (m *CommentCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentCreateRequest.Marshal(b, m, deterministic)
}
func (m *CommentCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentCreateRequest.Merge(m, src)
}
func (m *CommentCreateRequest) XXX_Size() int {
	return xxx_messageInfo_CommentCreateRequest.Size(m)
}
func (m *CommentCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentCreateRequest proto.InternalMessageInfo

func (m *CommentCreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CommentCreateRequest) GetStoryId() string {
	if m != nil {
		return m.StoryId
	}
	return ""
}

func (m *CommentCreateRequest) GetTextContent() string {
	if m != nil {
		return m.TextContent
	}
	return ""
}

func (m *CommentCreateRequest) GetCommentator() string {
	if m != nil {
		return m.Commentator
	}
	return ""
}

func (m *CommentCreateRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type CommentCreateResponse struct {
	// UUID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentCreateResponse) Reset()         { *m = CommentCreateResponse{} }
func (m *CommentCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CommentCreateResponse) ProtoMessage()    {}
func (*CommentCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_359215752d6d6d81, []int{1}
}

func (m *CommentCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentCreateResponse.Unmarshal(m, b)
}
func (m *CommentCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentCreateResponse.Marshal(b, m, deterministic)
}
func (m *CommentCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentCreateResponse.Merge(m, src)
}
func (m *CommentCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CommentCreateResponse.Size(m)
}
func (m *CommentCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentCreateResponse proto.InternalMessageInfo

func (m *CommentCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CommentCreateRequest)(nil), "CommentCreateRequest")
	proto.RegisterType((*CommentCreateResponse)(nil), "CommentCreateResponse")
}

func init() { proto.RegisterFile("comment_message.proto", fileDescriptor_359215752d6d6d81) }

var fileDescriptor_359215752d6d6d81 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4b, 0x03, 0x31,
	0x14, 0xc6, 0xc9, 0x59, 0xaa, 0xbe, 0x82, 0x43, 0xb0, 0x10, 0xba, 0x78, 0x74, 0xb1, 0x53, 0x0a,
	0xba, 0xe9, 0xe6, 0x4d, 0xae, 0x47, 0x27, 0x17, 0xc9, 0xf5, 0x9e, 0x47, 0xc0, 0xe4, 0xc5, 0xe4,
	0x15, 0xf4, 0xbf, 0xf3, 0x4f, 0x13, 0x93, 0x1e, 0x1c, 0x37, 0x7e, 0x5f, 0x7e, 0x49, 0x7e, 0x1f,
	0xac, 0x8f, 0xe4, 0x1c, 0x7a, 0x7e, 0x77, 0x98, 0x92, 0x19, 0x50, 0x87, 0x48, 0x4c, 0x9b, 0xbb,
	0x81, 0x68, 0xf8, 0xc4, 0x7d, 0x4e, 0xdd, 0xe9, 0x63, 0xcf, 0xd6, 0x61, 0x62, 0xe3, 0x42, 0x01,
	0xb6, 0xbf, 0x02, 0x6e, 0x9b, 0x72, 0xb5, 0x89, 0x68, 0x18, 0x5b, 0xfc, 0x3a, 0x61, 0x62, 0x79,
	0x03, 0x95, 0xed, 0x95, 0xa8, 0xc5, 0xee, 0xba, 0xad, 0x6c, 0x2f, 0x15, 0x5c, 0x26, 0xa6, 0xf8,
	0xf3, 0xda, 0xab, 0x2a, 0x97, 0x63, 0x94, 0x35, 0xac, 0x18, 0xbf, 0xb9, 0x21, 0xcf, 0xe8, 0x59,
	0x5d, 0xe4, 0xd3, 0x69, 0xf5, 0x4f, 0x9c, 0xf5, 0x0c, 0x53, 0x54, 0x8b, 0x42, 0x4c, 0x2a, 0xf9,
	0x04, 0x70, 0xcc, 0xdf, 0x1f, 0xac, 0x43, 0x75, 0x55, 0x8b, 0xdd, 0xea, 0x61, 0xa3, 0x8b, 0xbc,
	0x1e, 0xe5, 0xf5, 0x61, 0x94, 0x6f, 0x27, 0xf4, 0xf6, 0x1e, 0xd6, 0xb3, 0x05, 0x29, 0x90, 0x4f,
	0x38, 0x9f, 0xf0, 0xb2, 0x7c, 0x5b, 0xe8, 0xe7, 0xd0, 0x75, 0xcb, 0xfc, 0xe0, 0xe3, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbe, 0x64, 0x73, 0xed, 0x34, 0x01, 0x00, 0x00,
}
