// Code generated by protoc-gen-go. DO NOT EDIT.
// source: story_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateStoryRequest struct {
	Story                *Story   `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoryRequest) Reset()         { *m = CreateStoryRequest{} }
func (m *CreateStoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStoryRequest) ProtoMessage()    {}
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0056fc2bdd0e5, []int{0}
}

func (m *CreateStoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoryRequest.Unmarshal(m, b)
}
func (m *CreateStoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoryRequest.Marshal(b, m, deterministic)
}
func (m *CreateStoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoryRequest.Merge(m, src)
}
func (m *CreateStoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStoryRequest.Size(m)
}
func (m *CreateStoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoryRequest proto.InternalMessageInfo

func (m *CreateStoryRequest) GetStory() *Story {
	if m != nil {
		return m.Story
	}
	return nil
}

type CreateStoryResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoryResponse) Reset()         { *m = CreateStoryResponse{} }
func (m *CreateStoryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStoryResponse) ProtoMessage()    {}
func (*CreateStoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41e0056fc2bdd0e5, []int{1}
}

func (m *CreateStoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoryResponse.Unmarshal(m, b)
}
func (m *CreateStoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoryResponse.Marshal(b, m, deterministic)
}
func (m *CreateStoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoryResponse.Merge(m, src)
}
func (m *CreateStoryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStoryResponse.Size(m)
}
func (m *CreateStoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoryResponse proto.InternalMessageInfo

func (m *CreateStoryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateStoryRequest)(nil), "CreateStoryRequest")
	proto.RegisterType((*CreateStoryResponse)(nil), "CreateStoryResponse")
}

func init() { proto.RegisterFile("story_service.proto", fileDescriptor_41e0056fc2bdd0e5) }

var fileDescriptor_41e0056fc2bdd0e5 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0xc9, 0x2f,
	0xaa, 0x8c, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97,
	0x82, 0x0a, 0xe6, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0x43, 0x05, 0x95, 0x8c, 0xb8, 0x84, 0x9c, 0x8b,
	0x52, 0x13, 0x4b, 0x52, 0x83, 0x41, 0x92, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32,
	0x5c, 0xac, 0x60, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x6c, 0x7a, 0x10, 0x59, 0x88,
	0xa0, 0x92, 0x2a, 0x97, 0x30, 0x8a, 0x9e, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e,
	0xa6, 0xcc, 0x14, 0xb0, 0x0e, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0xa3, 0x7d, 0x8c, 0x5c, 0x3c, 0x60,
	0x15, 0xc1, 0x10, 0x67, 0x08, 0x99, 0x72, 0xb1, 0x41, 0xf4, 0x09, 0x09, 0xeb, 0x61, 0x5a, 0x2a,
	0x25, 0xa2, 0x87, 0xc5, 0x54, 0x25, 0x06, 0x21, 0x07, 0x2e, 0x4e, 0xf7, 0xd4, 0x12, 0x9f, 0xc4,
	0x12, 0x90, 0xcb, 0xc4, 0xf4, 0xe0, 0x6c, 0x14, 0xcd, 0xe2, 0x18, 0xe2, 0x30, 0xfd, 0x06, 0x8c,
	0x20, 0x8b, 0x43, 0x0b, 0x52, 0x20, 0x16, 0x43, 0x18, 0x68, 0x16, 0xa3, 0x08, 0xc2, 0x34, 0x3a,
	0xb1, 0x45, 0xb1, 0xe8, 0x59, 0x17, 0x24, 0x25, 0xb1, 0x81, 0x83, 0xca, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xd7, 0x89, 0x96, 0xed, 0x56, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoryServiceClient is the client API for StoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoryServiceClient interface {
	Create(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*CreateStoryResponse, error)
	GetLatest(ctx context.Context, in *GetLatestStoryRequest, opts ...grpc.CallOption) (StoryService_GetLatestClient, error)
	Update(ctx context.Context, in *UpdateStoryRequest, opts ...grpc.CallOption) (*UpdateStoryResponse, error)
}

type storyServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoryServiceClient(cc *grpc.ClientConn) StoryServiceClient {
	return &storyServiceClient{cc}
}

func (c *storyServiceClient) Create(ctx context.Context, in *CreateStoryRequest, opts ...grpc.CallOption) (*CreateStoryResponse, error) {
	out := new(CreateStoryResponse)
	err := c.cc.Invoke(ctx, "/StoryService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) GetLatest(ctx context.Context, in *GetLatestStoryRequest, opts ...grpc.CallOption) (StoryService_GetLatestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoryService_serviceDesc.Streams[0], "/StoryService/GetLatest", opts...)
	if err != nil {
		return nil, err
	}
	x := &storyServiceGetLatestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoryService_GetLatestClient interface {
	Recv() (*GetLatestStoryResponse, error)
	grpc.ClientStream
}

type storyServiceGetLatestClient struct {
	grpc.ClientStream
}

func (x *storyServiceGetLatestClient) Recv() (*GetLatestStoryResponse, error) {
	m := new(GetLatestStoryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storyServiceClient) Update(ctx context.Context, in *UpdateStoryRequest, opts ...grpc.CallOption) (*UpdateStoryResponse, error) {
	out := new(UpdateStoryResponse)
	err := c.cc.Invoke(ctx, "/StoryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoryServiceServer is the server API for StoryService service.
type StoryServiceServer interface {
	Create(context.Context, *CreateStoryRequest) (*CreateStoryResponse, error)
	GetLatest(*GetLatestStoryRequest, StoryService_GetLatestServer) error
	Update(context.Context, *UpdateStoryRequest) (*UpdateStoryResponse, error)
}

// UnimplementedStoryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoryServiceServer struct {
}

func (*UnimplementedStoryServiceServer) Create(ctx context.Context, req *CreateStoryRequest) (*CreateStoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedStoryServiceServer) GetLatest(req *GetLatestStoryRequest, srv StoryService_GetLatestServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLatest not implemented")
}
func (*UnimplementedStoryServiceServer) Update(ctx context.Context, req *UpdateStoryRequest) (*UpdateStoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterStoryServiceServer(s *grpc.Server, srv StoryServiceServer) {
	s.RegisterService(&_StoryService_serviceDesc, srv)
}

func _StoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StoryService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).Create(ctx, req.(*CreateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoryService_GetLatest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLatestStoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoryServiceServer).GetLatest(m, &storyServiceGetLatestServer{stream})
}

type StoryService_GetLatestServer interface {
	Send(*GetLatestStoryResponse) error
	grpc.ServerStream
}

type storyServiceGetLatestServer struct {
	grpc.ServerStream
}

func (x *storyServiceGetLatestServer) Send(m *GetLatestStoryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StoryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoryServiceServer).Update(ctx, req.(*UpdateStoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StoryService",
	HandlerType: (*StoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _StoryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StoryService_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLatest",
			Handler:       _StoryService_GetLatest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "story_service.proto",
}
